# Generated by Django 3.1.3 on 2020-11-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0132_seat_instructions_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Meta_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('testing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Active_Docs_View',
        ),
        migrations.DeleteModel(
            name='Archive_Docs_View',
        ),
        migrations.AddField(
            model_name='document_type_module',
            name='is_main_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doc_approval',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark_demand',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_demands', to='edms.document'),
        ),
        migrations.AlterField(
            model_name='mark_demand',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mark_demands', to='edms.mark'),
        ),
        migrations.AddField(
            model_name='document_type',
            name='meta_doc_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='doc_types', to='edms.document_meta_type'),
        ),
    ]
