# Generated by Django 3.1.4 on 2020-12-11 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0133_auto_20201207_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='edms.document')),
            ],
        ),
    ]
