# Generated by Django 3.1.4 on 2020-12-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0134_doc_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.CharField(blank=True, default='ТДВ', max_length=3, null=True),
        ),
    ]
