# Generated by Django 3.1.4 on 2020-12-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0135_auto_20201218_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_contract',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract', to='edms.document'),
        ),
    ]
