# Generated by Django 3.1.4 on 2021-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0136_auto_20201223_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stage',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
