# Generated by Django 3.1.4 on 2021-01-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_access_to_all_contracts'),
        ('edms', '0137_document_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Doc_Type_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='view_doc_types_permissions', to='accounts.userprofile')),
                ('meta_doc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users_with_view_permission', to='edms.document_meta_type')),
            ],
        ),
    ]
