# Generated by Django 3.1.4 on 2021-02-18 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_access_to_all_contracts'),
        ('edms', '0140_user_doc_type_view_send_mails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Type_Create_Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_type_create_rights', to='accounts.department')),
                ('document_meta_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_rights', to='edms.document_meta_type')),
                ('emp_seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_type_create_rights', to='edms.employee_seat')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_type_create_rights', to='edms.seat')),
            ],
        ),
    ]
