# Generated by Django 3.1.4 on 2021-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0141_doc_type_create_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_type_module',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
