# Generated by Django 3.1.4 on 2021-03-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0021_auto_20210317_1656'),
        ('boards', '0013_auto_20210318_1137'),
        ('edms', '0142_document_type_module_hide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doc_client',
            new_name='Doc_Client_deprecated',
        ),
        migrations.CreateModel(
            name='Doc_Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='edms_documents', to='boards.counterparty')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='counterparty', to='edms.document')),
            ],
        ),
    ]
