# Generated by Django 3.1.4 on 2021-03-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20210323_1515'),
        ('edms', '0142_document_type_module_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_client',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='edms.document'),
        ),
        migrations.CreateModel(
            name='Doc_Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='edms_documents', to='boards.counterparty')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='counterparty', to='edms.document')),
            ],
        ),
    ]
