# Generated by Django 3.1.4 on 2021-04-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20210323_1515'),
        ('edms', '0143_auto_20210323_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_counterparty',
            name='counterparty_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doc_counterparty',
            name='counterparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edms_documents', to='boards.counterparty'),
        ),
    ]
