# Generated by Django 3.1.4 on 2021-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0147_user_doc_type_view_super_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_requirements',
            name='binding',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
