# Generated by Django 3.1.4 on 2021-07-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0149_client_requirement_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doc_registration', to='edms.document')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Doc_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doc_links', to='edms.document')),
                ('document_link', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='links_for', to='edms.document')),
            ],
        ),
    ]
