# Generated by Django 3.1.13 on 2021-09-08 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0150_doc_doc_link_doc_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Datetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('queue_in_doc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='datetimes', to='edms.document')),
            ],
        ),
    ]
