# Generated by Django 3.1.13 on 2021-10-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20211011_1032'),
        ('edms', '0150_doc_doc_link_doc_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_datetime', models.DateTimeField(null=True)),
                ('in_datetime', models.DateTimeField(null=True)),
                ('absence_based', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('edms_doc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foyer', to='edms.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foyer', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Document_Type_Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='edms.document_type')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Foyer_Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_datetime', models.DateTimeField(null=True)),
                ('in_datetime', models.DateTimeField(null=True)),
                ('queue_in_doc', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foyer_ranges', to='edms.document')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_in_doc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='edms.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='accounts.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='edms.document_type_version'),
        ),
        migrations.AddField(
            model_name='document_type_module',
            name='doc_type_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='type_modules', to='edms.document_type_version'),
        ),
        migrations.AlterField(
            model_name='doc_type_phase',
            name='doc_type_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='doc_type_phases', to='edms.document_type_version'),
        ),
    ]
