# Generated by Django 3.1.13 on 2021-09-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0151_doc_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type_version',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Document_Type_Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='edms.document_type')),
            ],
        ),
    ]
