# Generated by Django 3.1.13 on 2021-09-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0152_auto_20210915_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_type_module',
            name='doc_type_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='type_modules', to='edms.document_type_version'),
        ),
    ]
