# Generated by Django 3.1.13 on 2022-06-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0153_auto_20220401_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_registration',
            name='registration_number',
            field=models.CharField(default=666, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
