# Generated by Django 3.1.13 on 2022-06-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0021_auto_20210608_1155'),
        ('production', '0006_cost_rates_nom_cost_rates_product'),
        ('edms', '0153_auto_20220401_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('accounting', models.CharField(max_length=1)),
                ('product_type', models.CharField(max_length=1)),
                ('date_start', models.CharField(max_length=30)),
                ('signed', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cost_rates', to='correspondence.client')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cost_rates', to='edms.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cost_rates', to='production.cost_rates_product')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Rates_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=10, null=True)),
                ('norm_for_one_t', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_rates', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fields', to='edms.cost_rates')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cost_rates', to='production.cost_rates_nom')),
            ],
        ),
    ]
