# Generated by Django 3.1.13 on 2021-09-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0154_auto_20210930_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Foyer_Datetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_datetime', models.DateTimeField(null=True)),
                ('enter_datetime', models.DateTimeField(null=True)),
                ('queue_in_doc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foyer_datetimes', to='edms.document')),
            ],
        ),
        migrations.DeleteModel(
            name='Doc_Datetime',
        ),
    ]
