# Generated by Django 3.1.13 on 2022-06-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_cost_rates_nom_cost_rates_product'),
        ('boards', '0011_counterparty_commentary'),
        ('edms', '0154_auto_20220616_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('accounting', models.CharField(max_length=1)),
                ('product_type', models.CharField(max_length=1)),
                ('date_start', models.DateField(null=True)),
                ('signed', models.BooleanField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cost_rates', to='boards.counterparty')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cost_rates', to='edms.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cost_rates', to='production.cost_rates_product')),
            ],
        ),
        migrations.AddField(
            model_name='document_type',
            name='is_deactivatable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Cost_Rates_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=10, null=True)),
                ('norm', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_rates', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fields', to='edms.cost_rates')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cost_rates', to='production.cost_rates_nom')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Rates_Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('term', models.CharField(blank=True, max_length=10, null=True)),
                ('norm', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_rates', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='additional_fields', to='edms.cost_rates')),
            ],
        ),
    ]
