# Generated by Django 3.1.13 on 2022-07-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0155_auto_20220628_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='main_field',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responsible_for_documents', to='edms.employee_seat'),
        ),
    ]
