# Generated by Django 3.1.13 on 2021-10-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0155_auto_20210930_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_foyer_datetime',
            name='queue_in_doc',
            field=models.IntegerField(null=True),
        ),
    ]
