# Generated by Django 3.1.13 on 2022-06-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0155_cost_rates_cost_rates_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Rates_Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('term', models.CharField(blank=True, max_length=10, null=True)),
                ('norm', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_rates', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='additional_fields', to='edms.cost_rates')),
            ],
        ),
    ]
