# Generated by Django 3.1.13 on 2022-09-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_contract_subject'),
        ('edms', '0156_auto_20220718_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Subject_To_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_work_for_contract_subject', to='edms.employee_seat')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_work_recipients', to='production.contract_subject')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Subject_Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approval_for_contract_subject', to='edms.employee_seat')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approval_recipients', to='production.contract_subject')),
            ],
        ),
    ]
