# Generated by Django 3.1.13 on 2022-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0156_cost_rates_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_rates',
            name='signed',
            field=models.BooleanField(null=True),
        ),
    ]
