# Generated by Django 3.1.13 on 2022-10-03 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_contract_subject'),
        ('edms', '0157_contract_subject_approval_contract_subject_to_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deadline', to='edms.document')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Contract_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('contract_subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='production.contract_subject')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract_subject', to='edms.document')),
            ],
        ),
    ]
