# Generated by Django 3.1.13 on 2021-10-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210719_1437'),
        ('edms', '0157_auto_20211004_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_in_doc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='edms.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doc_employee_docs', to='accounts.userprofile')),
            ],
        ),
    ]
