# Generated by Django 3.1.13 on 2022-10-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_vacation'),
        ('edms', '0158_doc_contract_subject_doc_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='acting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='acting_for_depr', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vacations_depr', to='accounts.userprofile'),
        ),
    ]
