# Generated by Django 3.1.13 on 2021-10-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0158_doc_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Foyer_Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_datetime', models.DateTimeField(null=True)),
                ('in_datetime', models.DateTimeField(null=True)),
                ('queue_in_doc', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foyer_ranges', to='edms.document')),
            ],
        ),
        migrations.DeleteModel(
            name='Doc_Foyer_Datetime',
        ),
    ]
