# Generated by Django 3.1.13 on 2022-10-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_contract_subject'),
        ('edms', '0158_doc_contract_subject_doc_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_contract_subject',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doc_contract_subject',
            name='contract_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='production.contract_subject'),
        ),
    ]
