# Generated by Django 3.1.13 on 2021-10-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210719_1437'),
        ('edms', '0159_auto_20211005_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_datetime', models.DateTimeField(null=True)),
                ('in_datetime', models.DateTimeField(null=True)),
                ('absence_based', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('edms_doc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foyer', to='edms.document')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foyer', to='accounts.userprofile')),
            ],
        ),
    ]
