# Generated by Django 3.1.13 on 2022-10-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0159_auto_20221011_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decree_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('term', models.CharField(default='term', max_length=8)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('periodicity', models.CharField(blank=True, max_length=1, null=True)),
                ('all_chiefs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='edms.document')),
            ],
        ),
        migrations.CreateModel(
            name='Decree_Article_Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responsibles', to='edms.decree_article')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responsible_for_decree_articles', to='edms.employee_seat')),
            ],
        ),
    ]
