# Generated by Django 3.1.13 on 2023-04-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0161_auto_20221020_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_doc_link',
            name='module',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.RESTRICT, related_name='doc_links', to='edms.module'),
            preserve_default=False,
        ),
    ]
