# Generated by Django 3.1.13 on 2021-10-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210719_1437'),
        ('edms', '0161_auto_20211005_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_employee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='accounts.userprofile'),
        ),
    ]
