# Generated by Django 3.1.14 on 2023-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0162_doc_doc_link_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_type_phase',
            name='plus_approval_by_chief',
            field=models.BooleanField(default=False),
        ),
    ]
