# Generated by Django 3.1.14 on 2024-01-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0163_doc_type_phase_plus_approval_by_chief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Integer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField(null=True)),
                ('queue_in_doc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='integers', to='edms.document')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Decimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('queue_in_doc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='decimals', to='edms.document')),
            ],
        ),
    ]
