# Generated by Django 4.2.11 on 2024-03-28 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_permission_file'),
        ('edms', '0164_doc_decimal_doc_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=30)),
                ('bag_type', models.CharField(max_length=45)),
                ('length', models.CharField(max_length=3)),
                ('width', models.CharField(max_length=3)),
                ('depth', models.CharField(max_length=3)),
                ('density', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=3)),
                ('material', models.CharField(max_length=400)),
                ('layers', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('author_comment', models.CharField(max_length=1000)),
                ('samples_are_available', models.BooleanField(default=True, null=True)),
                ('bag_name', models.CharField(max_length=100, null=True)),
                ('weight_kg', models.CharField(max_length=10, null=True)),
                ('mf_water', models.CharField(max_length=10, null=True)),
                ('mf_ash', models.CharField(max_length=10, null=True)),
                ('mf_evaporable', models.CharField(max_length=10, null=True)),
                ('mf_not_evaporable_carbon', models.CharField(max_length=10, null=True)),
                ('main_faction', models.CharField(max_length=10, null=True)),
                ('granulation_lt5', models.CharField(max_length=10, null=True)),
                ('granulation_lt10', models.CharField(max_length=10, null=True)),
                ('granulation_lt20', models.CharField(max_length=10, null=True)),
                ('granulation_lt25', models.CharField(max_length=10, null=True)),
                ('granulation_lt40', models.CharField(max_length=10, null=True)),
                ('granulation_mt20', models.CharField(max_length=10, null=True)),
                ('granulation_mt60', models.CharField(max_length=10, null=True)),
                ('granulation_mt80', models.CharField(max_length=10, null=True)),
                ('test_start_date', models.DateField(null=True)),
                ('test_end_date', models.DateField(null=True)),
                ('test_conclusion_date', models.DateField(null=True)),
                ('meets_tech_specs', models.BooleanField(default=True, null=True)),
                ('meets_certificate', models.BooleanField(default=True, null=True)),
                ('meets_dimensions', models.BooleanField(default=True, null=True)),
                ('meets_density', models.BooleanField(default=True, null=True)),
                ('meets_client_requirements', models.BooleanField(default=True, null=True)),
                ('tech_conditions_are_in_certificate', models.BooleanField(default=True, null=True)),
                ('test_conclusion', models.BooleanField(default=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_bag_tests', to='boards.counterparty')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bag_test', to='edms.document')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='provider_bag_tests', to='boards.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Bag_Test_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=35)),
                ('file', models.FileField(upload_to='edms_files/%Y/%m')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bag_test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='edms.bag_test')),
            ],
        ),
        migrations.CreateModel(
            name='Bag_Test_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=35)),
                ('comment', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('bag_test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='edms.bag_test')),
            ],
        ),
    ]
