# Generated by Django 4.2.11 on 2024-04-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0165_bag_test_bag_test_file_bag_test_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_type_module',
            name='columns',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='document_type_module',
            name='additional_info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
