# Generated by Django 4.2.11 on 2024-04-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0165_bag_test_bag_test_file_bag_test_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_test',
            name='client_requirements_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bag_test_from_this_cr', to='edms.document'),
        ),
    ]
