# Generated by Django 4.2.11 on 2024-06-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0166_document_type_module_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='queue_in_doc',
            field=models.IntegerField(null=True),
        ),
    ]
