# Generated by Django 4.2.11 on 2024-05-03 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0166_document_type_module_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_in_doc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seats', to='edms.document')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='edms.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Boolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=False)),
                ('queue_in_doc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booleans', to='edms.document')),
            ],
        ),
    ]
