# Generated by Django 4.2.11 on 2024-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0166_bag_test_client_requirements_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_test',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
