# Generated by Django 4.2.11 on 2024-04-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0167_bag_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag_test',
            old_name='test_conclusion',
            new_name='sample_is_compliant',
        ),
        migrations.RenameField(
            model_name='bag_test',
            old_name='test_conclusion_date',
            new_name='test_date',
        ),
        migrations.RenameField(
            model_name='bag_test',
            old_name='test_end_date',
            new_name='test_report_date',
        ),
        migrations.RemoveField(
            model_name='bag_test',
            name='test_start_date',
        ),
        migrations.AlterField(
            model_name='bag_test_comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
