# Generated by Django 4.2.11 on 2024-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0167_file_queue_in_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_type_phase',
            name='only_first',
            field=models.BooleanField(default=False),
        ),
    ]
