# Generated by Django 4.2.11 on 2024-05-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0168_rename_boolean_doc_boolean_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc_seat',
            name='queue_in_doc',
        ),
    ]
