# Generated by Django 4.2.11 on 2024-04-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0168_rename_test_conclusion_bag_test_sample_is_compliant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag_test',
            name='meets_certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bag_test',
            name='meets_client_requirements',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bag_test',
            name='meets_density',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bag_test',
            name='meets_dimensions',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bag_test',
            name='meets_tech_specs',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bag_test',
            name='sample_is_compliant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bag_test',
            name='tech_conditions_are_in_certificate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
