# Generated by Django 4.2.11 on 2024-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0169_alter_bag_test_meets_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag_test_comment',
            name='field_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='bag_test_file',
            name='field_name',
            field=models.CharField(max_length=45),
        ),
    ]
