# Generated by Django 3.1.13 on 2021-08-05 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0032_auto_20210719_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationery_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('measurement', models.CharField(default='шт.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stationery_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('month', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stationery_orders', to='accounts.userprofile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stationery_orders', to='accounts.department')),
                ('stationery_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='ordering.stationery_type')),
            ],
        ),
    ]
