# Generated by Django 3.1.4 on 2021-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='direction',
            field=models.CharField(default='sale', max_length=4),
        ),
    ]
