# Generated by Django 3.1.4 on 2021-04-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20210323_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sub_product_types', to='production.product_type')),
            ],
        ),
    ]
