# Generated by Django 3.1.13 on 2022-09-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_cost_rates_nom_cost_rates_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
