# Generated by Django 3.1.13 on 2022-06-20 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_cost_rates_product_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_rates_nom',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='fields', to='production.cost_rates_product'),
            preserve_default=False,
        ),
    ]
