# Generated by Django 3.1.13 on 2022-10-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_contract_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='production.product_type')),
            ],
        ),
    ]
