# Generated by Django 3.1.13 on 2023-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
