# Generated by Django 3.1.13 on 2022-06-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_cost_rates_nom_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_rates_nom',
            name='ua_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cost_rates_nom',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
