# Generated by Django 3.1.13 on 2022-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20220620_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost_rates_nom',
            name='ua_name',
        ),
        migrations.AlterField(
            model_name='cost_rates_nom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
