# Generated by Django 3.1.13 on 2022-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20220620_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_rates_nom',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
