# Generated by Django 3.1.13 on 2022-03-30 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0034_department_is_tdv'),
        ('edms', '0152_document_type_module_defines_doc_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=3)),
                ('version', models.CharField(max_length=3)),
                ('staff_units', models.CharField(max_length=3)),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_revision', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='regulations', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='Seat_Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=3)),
                ('version', models.CharField(max_length=3)),
                ('staff_units', models.CharField(max_length=3)),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_revision', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instructions', to='edms.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Regulation_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hr/regulations/%Y/%m')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='hr.department_regulation')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hr/regulations/%Y/%m')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='hr.seat_instruction')),
            ],
        ),
    ]
