# Generated by Django 3.1.14 on 2023-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20231124_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='type',
            field=models.CharField(default='seat', max_length=4),
            preserve_default=False,
        ),
    ]
