# Generated by Django 3.1.4 on 2021-03-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userprofile_providers_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_type_add',
            field=models.BooleanField(default=False),
        ),
    ]
