# Generated by Django 3.1.4 on 2021-06-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_userprofile_product_type_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scope_add',
            field=models.BooleanField(default=False),
        ),
    ]
