# Generated by Django 3.1.13 on 2021-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_userprofile_scope_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stationery_orders_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stationery_type_add',
            field=models.BooleanField(default=False),
        ),
    ]
