# Generated by Django 3.1.13 on 2021-09-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210719_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_tdv',
            field=models.BooleanField(default=True),
        ),
    ]
