# Generated by Django 3.1.13 on 2022-03-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20211011_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_tdv',
            field=models.BooleanField(default=True),
        ),
    ]
