# Generated by Django 3.1.13 on 2022-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_department_is_tdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dep_regulations_add',
            field=models.BooleanField(default=False),
        ),
    ]
