# Generated by Django 3.1.13 on 2022-06-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_userprofile_dep_regulations_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delete_from_noms',
            field=models.BooleanField(default=False),
        ),
    ]
