# Generated by Django 3.1.13 on 2022-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_userprofile_delete_from_noms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contract_subject_edit',
            field=models.BooleanField(default=False),
        ),
    ]
