# Generated by Django 3.1.13 on 2022-10-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_userprofile_contract_subject_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='corr_template_edit',
            field=models.BooleanField(default=False),
        ),
    ]
