# Generated by Django 3.1.13 on 2022-10-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='acting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='acting_for', to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
