# Generated by Django 3.1.13 on 2022-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20221011_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
