# Generated by Django 3.1.4 on 2020-12-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0133_auto_20201207_1001'),
        ('docs', '0029_order_article_first_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_responsible',
            name='employee_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders_articles_responsible', to='edms.employee_seat'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='edms_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edms_docs', to='edms.document'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
