# Generated by Django 3.1.4 on 2020-12-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0030_auto_20201209_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.CharField(blank=True, default='ТДВ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
