# Generated by Django 3.1.4 on 2021-01-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0031_auto_20201221_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_article',
            name='term',
            field=models.CharField(default='term', max_length=8),
        ),
    ]
