# Generated by Django 3.1.4 on 2021-04-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0033_auto_20210125_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='counterparty',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
