# Generated by Django 3.1.13 on 2022-10-21 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0161_auto_20221020_1631'),
        ('docs', '0034_auto_20210401_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_doc',
            name='edms_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_order', to='edms.document'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='edms_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_contract', to='edms.document'),
        ),
    ]
