# Generated by Django 3.1.13 on 2022-10-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0036_order_doc_preamble'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_doc',
            name='company',
            field=models.CharField(default='ТДВ', max_length=3),
        ),
    ]
