# Generated by Django 3.1.14 on 2023-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0036_auto_20221027_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_article',
            name='text',
            field=models.CharField(max_length=7000),
        ),
    ]
