# Generated by Django 4.2.11 on 2025-02-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_userprofile_permissions_edit'),
        ('boards', '0018_permission_file'),
        ('docs', '0038_contract_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_reg_number',
            name='counterparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contracts_reg_numbers', to='boards.counterparty'),
        ),
        migrations.AddField(
            model_name='contract_reg_number',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responsible_for_contract_reg_number', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='contract_reg_number',
            name='subject',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contract_reg_number',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
