# Generated by Django 4.2.11 on 2025-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0039_contract_reg_number_counterparty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_reg_number',
            name='company',
            field=models.CharField(default='ТОВ', max_length=3),
            preserve_default=False,
        ),
    ]
