# Generated by Django 4.2.20 on 2025-04-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0040_contract_reg_number_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_reg_number',
            name='sequence_number',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contract_reg_number',
            name='company',
            field=models.CharField(max_length=15),
        ),
    ]
