# Generated by Django 4.2.20 on 2025-05-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0041_contract_reg_number_sequence_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_reg_number',
            name='basic_contract_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='additional_contract_numbers', to='docs.contract_reg_number'),
        ),
    ]
