# Generated by Django 4.2.20 on 2025-05-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0168_doc_type_phase_only_first'),
        ('docs', '0042_contract_reg_number_basic_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_reg_number',
            name='edms_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_reg_number', to='edms.document'),
        ),
    ]
