# Generated by Django 3.1.4 on 2020-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0018_request_acquaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='unique_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
