# Generated by Django 3.1.4 on 2021-03-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20210323_1515'),
        ('production', '0004_auto_20210323_1513'),
        ('correspondence', '0019_request_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law_scope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='laws', to='production.scope'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='boards.counterparty'),
        ),
        migrations.AlterField(
            model_name='request',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='production.scope'),
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
