# Generated by Django 3.1.4 on 2021-03-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_scope'),
        ('correspondence', '0019_request_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law_scope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='laws', to='production.scope'),
        ),
        migrations.AlterField(
            model_name='request',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='production.scope'),
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
