# Generated by Django 3.1.13 on 2022-10-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0022_corr_templates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corr_Templates',
            new_name='Corr_Template',
        ),
    ]
