# Generated by Django 3.1.13 on 2022-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0023_auto_20221005_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='corr_template',
            name='file_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
