# Generated by Django 3.1.13 on 2022-10-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0024_corr_template_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corr_template',
            name='file',
        ),
        migrations.RemoveField(
            model_name='corr_template',
            name='file_name',
        ),
        migrations.AddField(
            model_name='corr_template',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Corr_Template_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='correspondence/corr_templates/%Y/%m')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('corr_template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='correspondence.corr_template')),
            ],
        ),
    ]
