# Generated by Django 2.0 on 2017-12-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='mobile1',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='mobile2',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='n_mobile',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='n_out',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='n_second',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
