# Generated by Django 3.1.4 on 2021-01-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_access_to_all_contracts'),
        ('production', '0003_product_type_direction'),
        ('boards', '0007_auto_20201119_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_provider', models.BooleanField(default=True)),
                ('legal_address', models.CharField(max_length=200, null=True)),
                ('actual_address', models.CharField(max_length=200, null=True)),
                ('added', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='providers_added', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty_certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
                ('number', models.CharField(max_length=20)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('old_plhk_number', models.CharField(max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certificates', to='boards.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='boards.counterparty')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='providers', to='production.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty_certificate_pause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_start', models.DateField(null=True)),
                ('pause_end', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pauses', to='boards.counterparty_certificate')),
            ],
        ),
    ]
