# Generated by Django 3.1.4 on 2021-02-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_counterparty_counterparty_certificate_counterparty_certificate_pause_counterparty_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='edrpou',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
