# Generated by Django 3.1.4 on 2021-03-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userprofile_providers_add'),
        ('production', '0004_auto_20210323_1513'),
        ('boards', '0008_counterparty_counterparty_certificate_counterparty_certificate_pause_counterparty_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty_certificate',
            name='type',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='bank_details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='contacts',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='edrpou',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='counterparties', to='production.product_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responsible', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='scope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='counterparties', to='production.scope'),
        ),
        migrations.AddField(
            model_name='counterparty_certificate',
            name='certification_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='certificates', to='production.certification_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty_certificate',
            name='declaration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counterparty_certificate',
            name='production_groups',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Counterparty_product',
        ),
    ]
