# Generated by Django 3.1.4 on 2021-02-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_certification_type'),
        ('boards', '0009_counterparty_edrpou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty_certificate',
            name='type',
        ),
        migrations.AddField(
            model_name='counterparty_certificate',
            name='certification_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='certificates', to='production.certification_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty_certificate',
            name='declaration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
