# Generated by Django 3.1.4 on 2021-06-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_sub_product_type'),
        ('accounts', '0030_userprofile_product_type_add'),
        ('boards', '0009_auto_20210323_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField()),
                ('dep_chief_approved', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('party_number', models.CharField(max_length=10)),
                ('order_number', models.CharField(max_length=10)),
                ('manufacture_date', models.DateField()),
                ('total_quantity', models.CharField(max_length=5)),
                ('nc_quantity', models.CharField(max_length=5)),
                ('packing_type', models.CharField(max_length=15)),
                ('reason', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('defect', models.CharField(max_length=100)),
                ('analysis_results', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('final_decision', models.CharField(max_length=100, null=True)),
                ('decision_date', models.DateField(null=True)),
                ('result_of_nc', models.CharField(max_length=100, null=True)),
                ('corrective_action', models.CharField(max_length=100, null=True)),
                ('corrective_action_number', models.CharField(max_length=10, null=True)),
                ('other', models.CharField(max_length=100, null=True)),
                ('retreatment_date', models.DateField(null=True)),
                ('spent_time', models.CharField(max_length=100, null=True)),
                ('people_involved', models.CharField(max_length=3, null=True)),
                ('quantity_updated', models.CharField(max_length=10, null=True)),
                ('status_updated', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='non_compliances_added', to='accounts.userprofile')),
                ('dep_chief', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dep_non_compliances', to='accounts.userprofile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='non_compliances', to='accounts.department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='non_compliances', to='production.product_type')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='non_compliances', to='boards.counterparty')),
            ],
        ),
    ]
