# Generated by Django 3.1.4 on 2021-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20210225_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty_certificate',
            name='production_groups',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
