# Generated by Django 3.1.4 on 2021-03-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_access_to_all_contracts'),
        ('production', '0005_scope'),
        ('boards', '0011_counterparty_certificate_production_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='bank_details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='contacts',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responsible', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='scope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='counterparties', to='production.scope'),
        ),
    ]
