# Generated by Django 3.1.4 on 2021-06-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_userprofile_scope_add'),
        ('boards', '0011_auto_20210611_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_compliance_approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('approved_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('non_compliance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approvals', to='boards.non_compliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='non_compliance_approvals', to='accounts.userprofile')),
            ],
        ),
    ]
