# Generated by Django 3.1.13 on 2022-10-06 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_counterparty_commentary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('counterparty_mail', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='letters', to='boards.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Letter_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='counterparties/letters/%Y/%m')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='boards.letter')),
            ],
        ),
    ]
