# Generated by Django 3.1.4 on 2021-06-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_non_compliance_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='non_compliance_approval',
            old_name='approved_time',
            new_name='recomendation_time',
        ),
        migrations.RemoveField(
            model_name='non_compliance_approval',
            name='approved',
        ),
        migrations.AddField(
            model_name='non_compliance_approval',
            name='comment',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='non_compliance_approval',
            name='recomendation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
