# Generated by Django 3.1.4 on 2021-03-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_scope'),
        ('boards', '0012_auto_20210315_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='counterparties', to='production.product_type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Counterparty_product',
        ),
    ]
