# Generated by Django 3.1.13 on 2023-03-18 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_userprofile_permissions_edit'),
        ('boards', '0014_permission_permission_date_permission_responsible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='permission_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='permission_responsible',
            name='revisioned',
        ),
        migrations.AddField(
            model_name='permission',
            name='date_next',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='permission_responsible',
            name='responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='responsible_for_permissions', to='accounts.userprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Permission_Date',
        ),
    ]
