# Generated by Django 3.1.4 on 2021-06-16 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_userprofile_scope_add'),
        ('boards', '0014_auto_20210616_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_compliance_decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=50, null=True)),
                ('decision_time', models.DateTimeField(null=True)),
                ('phase', models.CharField(default='1', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('non_compliance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='decisions', to='boards.non_compliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='non_compliance_decisions', to='accounts.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Non_compliance_approval',
        ),
    ]
