# Generated by Django 3.1.4 on 2021-06-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20210616_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_compliance_decision',
            name='phase',
            field=models.SmallIntegerField(default=1),
        ),
    ]
