# Generated by Django 3.1.4 on 2021-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_auto_20210623_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_compliance',
            name='decision_date',
        ),
        migrations.AddField(
            model_name='non_compliance',
            name='final_decision_time',
            field=models.DateTimeField(null=True),
        ),
    ]
