# Generated by Django 3.1.4 on 2021-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_auto_20210623_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_compliance',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='non_compliance',
            name='spent_time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
