# Generated by Django 3.1.14 on 2023-12-20 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_auto_20231203_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='permissions/%Y/%m')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='boards.permission')),
            ],
        ),
    ]
