# Generated by Django 3.1.4 on 2021-06-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20210624_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_compliance',
            name='other',
        ),
        migrations.RemoveField(
            model_name='non_compliance',
            name='result_of_nc',
        ),
    ]
