# Generated by Django 3.1.4 on 2021-06-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_auto_20210625_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_compliance',
            name='reason',
            field=models.CharField(max_length=300),
        ),
    ]
